[package]
name = "source-span"
version = "0.1.0"
authors = ["Timoth√©e Haudebourg <timothee.haudebourg@irisa.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
utf8-decode = "*"
